### ISSUE TITLE
Determine project

### ISSUE THREAD

**Issue by chuckfee23** [chuckfee23/project1-group5#1]

**Comment by chuckfee23** [comment]
As a team, we need to determine what we want to do as our project

**Comment by halliemestas** [comment]
Elevator Pitch: Our application allows you to search for ingredients, the search will provide a photo and nutritional facts.
Concept: A user wants more nutritional information regarding the food they are eating on a daily basis. 
Future development: Adding a suggested recipes widget for the item searched, what recipes it could be included in.
