### ISSUE TITLE
JS 2-functions with APIs

### ISSUE THREAD

**Issue by chuckfee23** [chuckfee23/project1-group5#5]

**Comment by mbottoms3** [comment]
Gabe

**Comment by myang5t3r** [comment]
API Library for Nutrition analysis: https://www.edamam.com/

API Library for images: https://www.pexels.com/discover/

**Comment by myang5t3r** [comment]
Example of Nutrition API : 
https://api.edamam.com/api/nutrition-data?app_id=ddbb3418&app_key=f821a94c134c496c176e82b63b0ade69&nutrition-type=logging&ingr=almond

Example of image api:

$ curl -H "Authorization: 563492ad6f917000010000010fed7dc8f9d54c5f92f832e19b404f62" \
> "https://api.pexels.com/v1/search?query=nature&per_page=1"
